version: '3'

services:
  frontend:
    image: okidijimmyjones/client:latest
    networks:
      - byte-genie
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    image: okidijimmyjones/byte-genie-server:latest
    networks:
      - byte-genie
    ports:
      - "8000:8000"


networks:
  byte-genie:
      
